### ISSUE TITLE
解决这个问题: BOOLEAN与asn.h中的冲突

### ISSUE THREAD

**Issue by FunHL** [QuantBox/XAPI2#16]
把以下代码：
// BOOLEAN与asn.h中的冲突，不得不将asn.h中的改了，希望有人帮忙解决这个问题
#include <windows.h>
#include <iphlpapi.h>
#pragma comment(lib, "IPHLPAPI.lib")
移到stdafx.h文件中就可以了！

风火论

**Comment by wukan1986** [comment]
非常棒，感谢
