### ISSUE TITLE
能不能给一个c#的例子订阅RB1710得到tick行情？

### ISSUE THREAD

**Issue by dcatcher9** [QuantBox/XAPI2#20]
这是我现在的代码。没法得到tick level 的market data。应该调用什么函数呢？

static void test_CTP_Main(string[] args)
        {
            //api = new XApi(@"C:\Program Files\SmartQuant Ltd\OpenQuant 2014\XAPI\CTP\x86\QuantBox_CTP_Quote.dll");

            api = new XApi(@"C:\Users\DCatcher\Source\Repos\XAPI2\bin\Debug\x86\CTP\CTP_Quote_x86.dll");

            api.Server.BrokerID = "9999";
            api.Server.Address = "tcp://180.168.146.187:10010";

            api.Server.PrivateTopicResumeType = ResumeType.Undefined;

            api.User.UserID = "";
            api.User.Password = "";

            api.OnConnectionStatus = OnConnectionStatus;
            api.OnRtnDepthMarketData = OnRtnDepthMarketData;
            api.OnRspQryInstrument = OnRspQryInstrument;
            api.OnRspQrySettlementInfo = OnRspQrySettlementInfo;

            api.Connect();
            Thread.Sleep(5 * 1000);
            
            api.Subscribe("RB1710", "");
            ReqQueryField query = default(ReqQueryField);
            query.InstrumentID = "RB1710";
            query.DateStart = 20170627;
            api.ReqQuery(QueryType.ReqQryHistoricalTicks, ref query);

            Thread.Sleep(10 * 1000);

            api.Dispose();

            Thread.Sleep(5 * 1000);

**Comment by wukan1986** [comment]
rb1710，中金所和郑商所大写，其它交易所小写

**Comment by ldd-Daniel** [comment]
@dcatcher9 @wukan1986 我用vs2012编译xapi2下面language下的CSharp，变异后在C:\Program Files\SmartQuant Ltd\OpenQuant 2014 下看到了XAPI_CSharp.exe，也可以通过设置，编译出dll文件，但是未能编译出CTP\CTP_Quote_x86.dll，导致跑不起来，这个问题应该怎样处理啊
