### ISSUE TITLE
CTP连接时报错：RuntimeError:can not open CFlow file

### ISSUE THREAD

**Issue by CodEFouR** [QuantBox/XAPI2#25]
使用.NET调用封装的C#接口：

```
api = new XApi("CTP_Quote_x64.dll");
api.Server.BrokerID = "8060";
api.Server.Address = "tcp://180.166.65.114:41213";
api.Server.PrivateTopicResumeType = ResumeType.Undefined;
api.User.UserID = "​user id";
api.User.Password = "password";
api.connect();
```
报错：
`RuntimeError:can not open CFlow file in line 256 of file ..\..\source\userapi\ThostFtdcUserApiImplBase.cpp`

**Comment by wukan1986** [comment]
检查流文件目录是否有读写权限

**Comment by weiyongh** [comment]
我用最老版本的java-ctp运行MdApiWrapper，也遇到这个类似错误，问一下怎么解决？流文件目录指的是哪个目录？

RuntimeError:can not open CFlow file in line 255 of file ..\..\source\userapi\ThostFtdcUserApiImplBase.cpp
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x163fe487, pid=5472, tid=0x00001e60
#
# JRE version: Java(TM) SE Runtime Environment (8.0_172-b11) (build 1.8.0_172-b11)
# Java VM: Java HotSpot(TM) Client VM (25.172-b11 mixed mode, sharing windows-x86 )
# Problematic frame:
# C  [thostmduserapi.dll+0x3e487]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\hwy\Documents\NetBeansProjects\CTP-master\Java-CTP\Java2CTP\hs_err_pid5472.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
