### ISSUE TITLE
我在 VS 2017下面 加入 总项目在编译UFX_Trade的时候报错

### ISSUE THREAD

**Issue by ershilang** [QuantBox/XAPI2#26]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开源文件: “stdafx.cpp”: No such file or directory	UFX_Trade	I:\SockProject\XAPI2-master\apis\UFX_Trade\c1xx	1	

另一个项目编译报错：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “libloaderapi.h”: No such file or directory	XAPI_CPP	i:\sockproject\xapi2-master\languages\cpp\xapi_cpp\xapic.cpp	10	

------------------
我是个C# 手。。。

楼主有没有解决方法？我觉得应该是缺少引用的文件 。。我 Ctrl F  找了整个solution 找不到这个类文件。（外面备注的两个压缩包也都找过。。木有）

**Comment by wukan1986** [comment]
不需要的项目不编译即可。
UFX_Trade不开源
